name: Release DenoDB Storage
 
on:
  push:
    tags:
      - "denodb*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - name: Run tests
        run: deno test packages/denodb/test/session.test.ts --unstable
      - name: Publish
        run: |
          deno install -Af --unstable https://x.nest.land/eggs@0.3.10/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          deno run --allow-read --allow-net --allow-env --unstable eggs.ts denodb