name: Release TypeOrm Storage
 
on:
  push:
    tags:
      - "typeorm*"
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i -g pnpm
      - run: pnpm install 
      - run: pnpm run build -- --scope=@grammyjs/grammy-typeorm-storage
      - run: pnpm run test -- --scope=@grammyjs/grammy-typeorm-storage
      - run: pnpm publish --filter=@grammyjs/grammy-typeorm-storage --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}