name: Tests PSQL Storage

on:
  push:
    paths:
      - packages/psql/**
  workflow_dispatch:

jobs:
  node-tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - name: install dependencies
        run: pnpm install 
      - name: build
        run: pnpm run build -- --scope=@grammyjs/storage-psql
      - name: tests
        run: pnpm run test -- --scope=@grammyjs/storage-psql
  deno-tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - name: Run tests
        run: deno test packages/psql/__tests__/deno.ts --unstable --no-check --allow-net