name: Tests MongoDB Storage

on:
  push:
    paths:
      - packages/mongodb/**
  workflow_dispatch:

jobs:
  node-tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - name: install dependencies
        run: pnpm install 
      - name: build
        run: pnpm run build -- --scope=@satont/grammy-mongodb-storage
      - name: tests
        run: pnpm run test -- --scope=@satont/grammy-mongodb-storage
  deno-tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    services:
      mongodb:
          image: mongo
          options: >-
            --health-cmd mongo
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 27017:27017
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - name: Run tests
        run: deno test packages/mongodb/__tests__/deno.ts --unstable --no-check --allow-net