name: Tests DenoDB Storage

on:
  push:
    paths:
      - packages/denodb/**
  workflow_dispatch:

jobs:
  tests:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: maximousblk/setup-deno@v1
      - run: deno -V
      - name: Run tests
        run: deno test packages/denodb/test/session.test.ts --unstable